name: Add Label

on:
  pull_request:
    types: [opened, edited]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install deps
        run: |
          yes | sudo apt update
          yes | sudo apt upgrade
          yes | sudo apt install python3
          yes | sudo apt install python3-pip
          yes | python3 -m pip install pyyaml
          yes | sudo apt install jq
      - name: determine owners
        id: determine_owners
        run: |
          echo "This PR is opened by ${{ github.event.pull_request.user.login }} ."
          OWNER_FILE_DATA=`curl https://raw.githubusercontent.com/barbacbd/RedHatDocs/main/OWNERS_ALIASES -o TMP_ALIASES`
          pyoutput=$(python3 -c '
          import json;
          import sys;
          import yaml;

          path = "./TMP_ALIASES";
          data = yaml.safe_load(open(path));
          searchUser = str(sys.argv[1])

          userTeam = None
          for team in data["aliases"]:
              if searchUser in data["aliases"][team]:
                  userTeam = team
                  break

          print(json.dumps({"team": userTeam}))' ${{ github.event.pull_request.user.login }})
          
          if [ -f TMP_ALIASES ]; then
            rm TMP_ALIASES
          fi

          team=$(echo $output | jq -r '.team')
          if [ "$team" == "null" ]; then
            echo "::set-output name=label::external-user-owned"
          else
            echo "::set-output name=label::$team"
          fi
      - name: print data
        run: |
	  echo "${{ steps.determine_owners.outputs.label }}"
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: ${{ steps.determine_owners.outputs.label }}
