# The following is a list of supported platforms,
# aws, gcp
# ALL CREDENTIAL INFORMATION is assumed to be in /home/$USER/.<platform>
platform: aws
# Regions should be provided according to the platform:
# aws: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions
# gcp: https://cloud.google.com/compute/docs/regions-zones
region: us-east1

# Base domain may be specific to the
base_domain: devcluster.openshift.com

# The secrets file contains all secrets for the installer
secrets_file: "/home/bbarbach/secrets/pull-secrets.txt"
# The keys are typically found in /home/$USER/.ssh/
ssh_key_file: "/home/bbarbach/.ssh/bbarbach.pub"

versions:
  installer: 4.9.5
  client: 4.9.5
  
installer:
  # location of the local version of openshift-installer
  dir: "/home/bbarbach/dev/installer"
  # image to use for Openshift 
  image: "quay.io/openshift-release-dev/ocp-release:4.10.10.x86_64"

docker:
  image_name: "installer-root-test"
  tag: "latest"

# This section is reserved for environment variables that should be included when creating the image
# The following are examples
# AWS_PROFILE: openshift-dev
# GOOGLE_APPLICATION_CREDENTIALS: ~/.gcp/gcp-key.json
env:
  AWS_PROFILE: openshift-dev
